### ISSUE TITLE
upgrade to emoji v12

### ISSUE THREAD

**Issue by Gummibeer** [spatie/emoji#33]
https://unicode.org/Public/emoji/12.0/emoji-test.txt
Using the generator #32 it should be easy to upgrade to Unicode Emoji v12 - but to make this work #32 should be merged.

**Comment by freekmurze** [comment]
I've used the generator to create the unicode emoji v12. I've pushed it to the `emoji-v12` branch.  The tests are failing. Could you take a look?

**Comment by Gummibeer** [comment]
I will.

**Comment by Gummibeer** [comment]
@freekmurze you haven't created the `emoji-v12` branch from `master`!? The changes from #28 are missing. I will fix it.

**Comment by Gummibeer** [comment]
PR #36 is open including the whole deprecation notice.

**Comment by freekmurze** [comment]
👍
