### ISSUE TITLE
Flags in Chrome

### ISSUE THREAD

**Issue by mangrovestudios** [spatie/emoji#46]
It seems that flag emojis are not showing in Chrome (using 86.0.4240.198). Firefox is ok.

![image](https://user-images.githubusercontent.com/35001/98940748-bc4cdb00-24eb-11eb-8b71-c53f1c1fc4ee.png)

```
Euro
{!! \Spatie\Emoji\Emoji::countryFlag('be') !!}
{!! \Spatie\Emoji\Emoji::grinningFace() !!}
```

What could be the reason? Am I missing something?

**Comment by freekmurze** [comment]
I don't know the reason. AFAIK we're just output the standard here.
