### ISSUE TITLE
Calling for Emoji Dynamically

### ISSUE THREAD

**Issue by ryangurn** [spatie/emoji#54]
I am using Laravel 8 and attempting to use a accessor to pull an icon (something like "CHARACTER_GRINNING_FACE") from the database and provide the icon. 

My desire is to handle this through the eloquent model.

When I tested getting an emoji (not dynamically) the icon is provided as expected. 
```php
dd(\Spatie\Emoji\Emoji::CHARACTER_GRINNING_FACE);
```

However when I attempt to add an accessor to my model I get an UnknownCharacter exception.

I have attempted to use the `getCharacter()` method on the emoji class, with no success.

The value passed into the accessor in this example is `CHARACTER_GRINNING_FACE`

```php
public function getIconAttribute($value)
{
    return Emoji::getCharacter($value);
}
```

I have also attempted to call the Emoji class as shown below, with no success.
```php
public function getIconAttribute($value)
{
    return call_user_func('\Spatie\Emoji\Emoji::'.$value);
}
```

-----
The error I get each time is the following.

Spatie\Emoji\Exceptions\UnknownCharacter
Character `CHARACTER_GRINNING_FACE` does not exist 

-----

Any advice you might have for getting the emoji character dynamically based on data in a database would be greatly appreciated.

**Comment by shegunbabs** [comment]
Here's how to get an emoji character dynamically.
You will need to use the `constant()` function

```
$emoji_constant = 'CHARACTER_GRINNING_FACE';
constant(
    sprintf("%s::%s, "\Spatie\Emoji\Emoji", $emoji_constant);
)
```

**Comment by ryangurn** [comment]
@shegunbabs  you are amazing! thanks so much!
