### ISSUE TITLE
Flag emoji incorrect code points

### ISSUE THREAD

**Issue by Omranic** [spatie/emoji#6]
http://unicode.org/emoji/charts/full-emoji-list.html
http://unicode.org/emoji/charts/index.html#col-code
> Some rows have more than one codepoint where a sequence is required, such as for flags and keycaps.

```php
echo Emoji::flagForBelgium();
```

So the previous code doesn't display the flag correctly, as it stores just the first codepoint for the flag `U+1F1E7`, that applies for all flags and keycaps. Any planned fix?

**Comment by freekmurze** [comment]
I'd gladly accept a PR that fixes this.

**Comment by Omranic** [comment]
If I could figure out some time for it, I'll gladly send a PR 👍

**Comment by freekmurze** [comment]
Fix by @Rias500 tagged as `v1.5.0`
